import type { PillarContent } from '../../../components/programme/PillarTemplate'

export const pillarContent: Record<string, PillarContent> = {
  '1': {
    title: 'Pillar 1: Community Flood Monitoring & Prevention',
    tagline: 'Empowering communities to become the first line of flood resilience.',
    heroImage: '/images/gcrfip_pillar1.png',
    overview: [
      'Community participation is central to sustainable flood resilience. Pillar 1 builds trusted local monitoring networks that capture early signals from neighborhoods, waterways, and vulnerable settlements.',
      'The pillar combines citizen observations, local rainfall tracking, and practical preparedness actions so communities can identify emerging risks and respond before impacts escalate.',
      'By linking local vigilance with national systems, Pillar 1 strengthens early warning reach, improves situational awareness, and supports faster, coordinated protection of lives and livelihoods.',
    ],
    focusAreas: [
      { code: 'MON', title: 'Community Flood Monitoring', description: 'Organizing local observation networks in flood-prone communities.' },
      { code: 'CRP', title: 'Citizen Reporting', description: 'Enabling real-time citizen reports of flood indicators and incidents.' },
      { code: 'EWS', title: 'Early Warning', description: 'Delivering timely alerts and practical warning guidance to residents.' },
      { code: 'RFO', title: 'Rainfall Observation', description: 'Tracking local rainfall patterns to detect evolving flood conditions.' },
      { code: 'LPR', title: 'Local Preparedness', description: 'Improving household and neighborhood readiness before flood events.' },
      { code: 'VNW', title: 'Volunteer Networks', description: 'Training community volunteers to support monitoring and response.' },
    ],
    workflow: ['Communities', 'Observation', 'Reporting', 'Early Warning', 'Prepared Communities'],
    featuredInitiatives: [
      { code: '1', title: 'Community Rain Gauge Network', description: 'Deploying locally managed rainfall stations in vulnerable zones.' },
      { code: '2', title: 'Citizen Reporting Platform', description: 'Establishing mobile and SMS channels for rapid incident reporting.' },
      { code: '3', title: 'Volunteer Monitoring Groups', description: 'Building trained local teams for grassroots flood vigilance.' },
    ],
    technologies: ['Mobile App', 'SMS Alerts', 'Rain Gauges', 'River Sensors', 'Community Dashboards'],
    expectedOutcomes: ['Improved Local Preparedness', 'Faster Warning Dissemination', 'Stronger Community Response', 'Reduced Local Flood Losses'],
    relatedDocuments: [
      { title: 'Technical Blueprint', href: '/programme/blueprint' },
      { title: 'Guidelines', href: '/resources/training-materials' },
      { title: 'Research Reports', href: '/resources/reports' },
      { title: 'Datasets', href: '/research/open-data' },
      { title: 'Policy Briefs', href: '/resources/policy-briefs' },
    ],
    relatedNews: [
      { title: 'Community Preparedness Campaign Expanded Across Regions', href: '/news/latest' },
      { title: 'Local Monitoring Volunteers Complete New Training Cycle', href: '/news/events' },
      { title: 'Flood Awareness Outreach Scales in Priority Districts', href: '/news/press-releases' },
    ],
    relatedGallery: [
      { src: '/images/flood_gallery2.png', alt: 'Community flood awareness activity', caption: 'Community-led awareness and preparedness action.' },
      { src: '/images/flood_gallery9.png', alt: 'Residents in flood-prone area', caption: 'Local observations support faster protective action.' },
      { src: '/images/flood_gallery4.png', alt: 'Volunteer flood response activity', caption: 'Volunteer networks strengthening early response.' },
    ],
    cta: {
      title: 'Strengthen Community Flood Readiness',
      description: 'Explore practical tools and partnerships that help communities monitor risk, report early, and prepare effectively.',
      primary: { title: 'Explore Get Involved', href: '/get-involved' },
      secondary: { title: 'View Preparedness Resources', href: '/resources/training-materials' },
    },
  },
  '2': {
    title: 'Pillar 2: Scientific Research & Flood Systems Understanding',
    tagline: 'Advancing flood science through integrated research and technology innovation.',
    heroImage: '/images/gcrfip_pillar2.png',
    overview: [
      'Scientific research is the foundation of effective flood resilience. Pillar 2 strengthens Ghana\'s ability to understand flood behaviour through multidisciplinary research, environmental monitoring, climate science, hydrological modelling, and emerging technologies.',
      'By integrating field observations, satellite imagery, Earth observation, geospatial analysis, artificial intelligence, and numerical modelling, this pillar generates the scientific knowledge needed to improve flood forecasting, hazard assessment, and long-term resilience planning.',
      'The knowledge produced under this pillar supports evidence-based policies, smarter infrastructure planning, and innovative flood intelligence systems that strengthen all other components of GCRFIP.',
    ],
    focusAreas: [
      { code: 'HYD', title: 'Flood Hydrology', description: 'Understanding rainfall-runoff dynamics, river behaviour, and drainage interactions.' },
      { code: 'CLI', title: 'Climate Science', description: 'Analyzing climate trends and their influence on flood frequency and intensity.' },
      { code: 'EO', title: 'Earth Observation', description: 'Using remote sensing to monitor flood-prone landscapes and change.' },
      { code: 'GIS', title: 'GIS & Spatial Analysis', description: 'Mapping hazard, exposure, and vulnerability through geospatial analytics.' },
      { code: 'AI', title: 'AI & Machine Learning', description: 'Developing intelligent forecasting methods for earlier warning.' },
      { code: 'HPC', title: 'High-Performance Computing', description: 'Accelerating simulations for operational flood intelligence.' },
    ],
    workflow: ['Data', 'Research', 'Models', 'Flood Intelligence'],
    featuredInitiatives: [
      { code: '1', title: 'National Flood Observatory', description: 'Establishing a harmonized research and evidence hub for flood systems.' },
      { code: '2', title: 'AI Flood Prediction', description: 'Combining model science and ML for higher forecast reliability.' },
      { code: '3', title: 'Climate Research Programme', description: 'Investigating climate-flood interactions to guide long-term planning.' },
    ],
    technologies: ['Python', 'ICON', 'Satellite Data', 'AI', 'GIS', 'Remote Sensing', 'Weather Radar'],
    expectedOutcomes: ['Improved Forecast Accuracy', 'Stronger Evidence Base', 'Smarter Infrastructure Decisions', 'Reduced Flood Losses'],
    relatedDocuments: [
      { title: 'Technical Blueprint', href: '/programme/blueprint' },
      { title: 'Guidelines', href: '/resources/training-materials' },
      { title: 'Research Reports', href: '/resources/reports' },
      { title: 'Datasets', href: '/research/open-data' },
      { title: 'Policy Briefs', href: '/resources/policy-briefs' },
    ],
    relatedNews: [
      { title: 'AI Model Successfully Tested in Northern Ghana', href: '/news/latest' },
      { title: 'University Partnership Expands Flood Research', href: '/news/blog' },
      { title: 'National Research Team Releases New Hazard Findings', href: '/news/press-releases' },
    ],
    relatedGallery: [
      { src: '/images/flood_gallery11.png', alt: 'Flood-affected infrastructure', caption: 'Field evidence supporting hydrological and infrastructure studies.' },
      { src: '/images/flood_reality3.png', alt: 'Flood impact corridor', caption: 'Research inputs for model calibration and risk interpretation.' },
      { src: '/images/flood_gallery12.png', alt: 'Urban flooding scene', caption: 'Urban flood dynamics informing forecasting improvements.' },
    ],
    cta: {
      title: 'Advance Science for National Flood Resilience',
      description: 'Explore the research ecosystem, technical assets, and collaborative initiatives driving next-generation flood intelligence.',
      primary: { title: 'Explore Research', href: '/research' },
      secondary: { title: 'Download Blueprint', href: '/resources/downloads' },
    },
  },
  '3': {
    title: 'Pillar 3: Smart Flood Intelligence & Decision Support',
    tagline: 'Transforming data streams into actionable intelligence for faster, better decisions.',
    heroImage: '/images/gcrfip_pillar3.png',
    overview: [
      'Pillar 3 operationalizes flood intelligence by connecting real-time monitoring, analytics, and forecasting into decision-ready outputs for institutions and response teams.',
      'It integrates sensor networks, geospatial dashboards, and forecasting systems to provide clear risk signals and practical guidance before and during flood events.',
      'By delivering trusted intelligence at speed, this pillar supports coordinated action, targeted resource allocation, and reduced exposure across communities and infrastructure systems.',
    ],
    focusAreas: [
      { code: 'RTM', title: 'Real-time Monitoring', description: 'Capturing live hydrometeorological and environmental conditions.' },
      { code: 'RS', title: 'Remote Sensing', description: 'Incorporating satellite observations for broader situational awareness.' },
      { code: 'GIS', title: 'GIS Dashboards', description: 'Visualizing dynamic flood information for operational teams.' },
      { code: 'FFC', title: 'Flood Forecasting', description: 'Producing near-term predictions and warning triggers.' },
      { code: 'DSS', title: 'Decision Support', description: 'Converting data outputs into actionable response options.' },
      { code: 'RIN', title: 'Risk Intelligence', description: 'Prioritizing high-risk locations, populations, and assets.' },
    ],
    workflow: ['Sensors', 'Analysis', 'Forecast', 'Decision Support'],
    featuredInitiatives: [
      { code: '1', title: 'Integrated Intelligence Dashboard', description: 'A unified operational dashboard for cross-agency awareness.' },
      { code: '2', title: 'Rapid Forecast Alert Service', description: 'Automated warning generation for high-impact flood signals.' },
      { code: '3', title: 'Decision Briefing Engine', description: 'Structured intelligence briefs for emergency and planning teams.' },
    ],
    technologies: ['Dashboards', 'Weather Radar', 'APIs', 'Decision Support', 'GIS', 'Remote Sensing'],
    expectedOutcomes: ['Faster Decisions', 'Improved Warning Lead Time', 'Better Resource Targeting', 'Reduced Operational Risk'],
    relatedDocuments: [
      { title: 'Technical Blueprint', href: '/programme/blueprint' },
      { title: 'Guidelines', href: '/resources/training-materials' },
      { title: 'Research Reports', href: '/resources/reports' },
      { title: 'Datasets', href: '/research/open-data' },
      { title: 'Policy Briefs', href: '/resources/policy-briefs' },
    ],
    relatedNews: [
      { title: 'Decision Dashboard Rolls Out to Regional Teams', href: '/news/latest' },
      { title: 'Forecast Workflow Enhancements Improve Alert Timing', href: '/news/events' },
      { title: 'New Intelligence Tools Support Emergency Coordination', href: '/news/press-releases' },
    ],
    relatedGallery: [
      { src: '/images/flood_gallery10.png', alt: 'Monitoring and response context', caption: 'Real-time intelligence supporting operational coordination.' },
      { src: '/images/flood_gallery13.png', alt: 'Flood observation context', caption: 'Live data streams feeding forecast and risk analysis.' },
      { src: '/images/flood_reality2.png', alt: 'Flood impact zone', caption: 'Targeted decision support for high-risk zones.' },
    ],
    cta: {
      title: 'Use Flood Intelligence to Act Earlier',
      description: 'Explore integrated monitoring, forecasting, and dashboard capabilities that strengthen operational decisions.',
      primary: { title: 'View Programme Overview', href: '/programme/overview' },
      secondary: { title: 'Explore Maps & Dashboards', href: '/resources/maps' },
    },
  },
  '4': {
    title: 'Pillar 4: Public Health, Sanitation & Community Resilience',
    tagline: 'Protecting health and dignity before, during, and after flood events.',
    heroImage: '/images/gcrfip_pillar4.png',
    overview: [
      'Pillar 4 addresses the health and sanitation dimensions of flood risk, ensuring communities can withstand, respond to, and recover from flood-related impacts.',
      'It strengthens emergency health preparedness, safe water and sanitation systems, disease surveillance, and coordinated response mechanisms in vulnerable areas.',
      'By linking health data, response planning, and recovery support, this pillar reduces secondary risks and improves long-term community resilience outcomes.',
    ],
    focusAreas: [
      { code: 'EHS', title: 'Emergency Health', description: 'Preparing health systems for flood-related surge and disruption.' },
      { code: 'WAS', title: 'Water & Sanitation', description: 'Safeguarding clean water access and sanitation continuity.' },
      { code: 'DIS', title: 'Disease Surveillance', description: 'Monitoring flood-linked outbreaks and public health threats.' },
      { code: 'EMR', title: 'Emergency Response', description: 'Coordinating rapid health and sanitation interventions.' },
      { code: 'REC', title: 'Community Recovery', description: 'Supporting recovery pathways for households and neighborhoods.' },
      { code: 'SAF', title: 'Public Safety', description: 'Strengthening protective communication and risk-reduction behaviors.' },
    ],
    workflow: ['Health Monitoring', 'Emergency Response', 'Recovery', 'Community Resilience'],
    featuredInitiatives: [
      { code: '1', title: 'Flood Health Risk Watch', description: 'Tracking and prioritizing health vulnerabilities during flood periods.' },
      { code: '2', title: 'Safe Water Continuity Plan', description: 'Maintaining critical water and sanitation services in affected areas.' },
      { code: '3', title: 'Community Recovery Support Package', description: 'Combining local response, referral, and resilience services.' },
    ],
    technologies: ['Health Reporting', 'WASH Monitoring', 'Rapid Assessment', 'Mobile Alerts', 'Response Coordination'],
    expectedOutcomes: ['Reduced Health Impacts', 'Safer Water & Sanitation', 'Faster Community Recovery', 'Stronger Household Resilience'],
    relatedDocuments: [
      { title: 'Technical Blueprint', href: '/programme/blueprint' },
      { title: 'Guidelines', href: '/resources/training-materials' },
      { title: 'Research Reports', href: '/resources/reports' },
      { title: 'Datasets', href: '/research/open-data' },
      { title: 'Policy Briefs', href: '/resources/policy-briefs' },
    ],
    relatedNews: [
      { title: 'Public Health Teams Strengthen Flood Season Readiness', href: '/news/latest' },
      { title: 'Sanitation Response Pilot Expands to New Districts', href: '/news/events' },
      { title: 'Community Recovery Partnerships Deliver Early Gains', href: '/news/blog' },
    ],
    relatedGallery: [
      { src: '/images/flood_gallery6.png', alt: 'Flood health impact context', caption: 'Health and sanitation priorities in flood-affected communities.' },
      { src: '/images/flood_gallery7.png', alt: 'Community response context', caption: 'Community response actions supporting safer recovery.' },
      { src: '/images/flood_reality4.png', alt: 'Flood resilience context', caption: 'Integrated support for public safety and resilience.' },
    ],
    cta: {
      title: 'Protect Health Through Flood Resilience',
      description: 'Explore integrated health, sanitation, and recovery actions that protect communities at risk.',
      primary: { title: 'Explore Community Programmes', href: '/get-involved' },
      secondary: { title: 'View Health & Resilience Resources', href: '/resources/reports' },
    },
  },
  '5': {
    title: 'Pillar 5: Governance & Institutional Strengthening',
    tagline: 'Building coordinated institutions that can deliver resilience at national scale.',
    heroImage: '/images/gcrfip_pillar5.png',
    overview: [
      'Pillar 5 strengthens governance systems required for consistent, accountable flood resilience delivery across ministries, agencies, and local institutions.',
      'It focuses on policy coherence, multi-agency coordination, implementation frameworks, and performance tracking to turn strategic intent into measurable outcomes.',
      'By reinforcing institutional capability and cross-sector alignment, this pillar enables durable resilience action and more effective public investment decisions.',
    ],
    focusAreas: [
      { code: 'POL', title: 'National Policy', description: 'Developing coherent policy direction for flood resilience delivery.' },
      { code: 'COO', title: 'Multi-Agency Coordination', description: 'Aligning institutions around shared operational priorities.' },
      { code: 'PLN', title: 'Planning Frameworks', description: 'Embedding risk intelligence in development and infrastructure planning.' },
      { code: 'GOV', title: 'Governance', description: 'Strengthening accountability and role clarity across systems.' },
      { code: 'MON', title: 'Performance Monitoring', description: 'Tracking delivery progress and institutional effectiveness.' },
      { code: 'INT', title: 'International Cooperation', description: 'Leveraging global partnerships, standards, and financing support.' },
    ],
    workflow: ['Government', 'Coordination', 'Policy', 'Implementation'],
    featuredInitiatives: [
      { code: '1', title: 'National Flood Governance Forum', description: 'Institutional platform for alignment and strategic oversight.' },
      { code: '2', title: 'Integrated Policy Translation Unit', description: 'Converting policy priorities into implementation action plans.' },
      { code: '3', title: 'Institutional Performance Scorecard', description: 'Monitoring cross-agency delivery quality and accountability.' },
    ],
    technologies: ['Policy Dashboards', 'Monitoring Frameworks', 'Data Portals', 'Interagency Workflows', 'Decision Logs'],
    expectedOutcomes: ['Stronger Institutional Coordination', 'Improved Delivery Accountability', 'Faster Policy Implementation', 'Sustained Resilience Investment'],
    relatedDocuments: [
      { title: 'Technical Blueprint', href: '/programme/blueprint' },
      { title: 'Guidelines', href: '/resources/training-materials' },
      { title: 'Research Reports', href: '/resources/reports' },
      { title: 'Datasets', href: '/research/open-data' },
      { title: 'Policy Briefs', href: '/resources/policy-briefs' },
    ],
    relatedNews: [
      { title: 'National Coordination Mechanism Enters New Phase', href: '/news/latest' },
      { title: 'Agency Performance Framework Adopted Across Units', href: '/news/press-releases' },
      { title: 'Institutional Strengthening Programme Announces Milestones', href: '/news/events' },
    ],
    relatedGallery: [
      { src: '/images/flood_gallery8.png', alt: 'Institutional coordination context', caption: 'Cross-agency planning and coordinated resilience governance.' },
      { src: '/images/flood_gallery5.png', alt: 'Risk governance context', caption: 'Policy and planning informed by flood intelligence.' },
      { src: '/images/flood_gallery1.png', alt: 'Urban flood governance context', caption: 'Governance action in high-risk urban flood environments.' },
    ],
    cta: {
      title: 'Strengthen Governance for Resilience Delivery',
      description: 'Explore the frameworks and institutional mechanisms advancing coordinated national flood resilience.',
      primary: { title: 'Explore Governance', href: '/about/governance' },
      secondary: { title: 'Read Policy Briefs', href: '/resources/policy-briefs' },
    },
  },
  '6': {
    title: 'Pillar 6: Capacity Building & Knowledge Transfer',
    tagline: 'Developing the people, skills, and networks needed for long-term resilience.',
    heroImage: '/images/gcrfip_pillar6.png',
    overview: [
      'Pillar 6 builds technical and institutional capability across government, academia, communities, and partner organizations to sustain flood resilience outcomes.',
      'It invests in professional training, practical learning programmes, workshops, and collaborative knowledge exchange to translate evidence into durable skills.',
      'By strengthening national capacity and innovation networks, this pillar ensures resilience systems can be operated, maintained, and continuously improved over time.',
    ],
    focusAreas: [
      { code: 'PRT', title: 'Professional Training', description: 'Developing operational and technical flood resilience competencies.' },
      { code: 'EDU', title: 'Education', description: 'Integrating flood science and resilience into learning pathways.' },
      { code: 'WSH', title: 'Workshops', description: 'Delivering applied knowledge and collaborative practice sessions.' },
      { code: 'KEX', title: 'Knowledge Exchange', description: 'Sharing lessons, methods, and tools across institutions.' },
      { code: 'ACA', title: 'Academic Partnerships', description: 'Building university and research institution collaboration pipelines.' },
      { code: 'INN', title: 'Innovation Networks', description: 'Accelerating solution development through multi-sector ecosystems.' },
    ],
    workflow: ['Training', 'Knowledge', 'Skills', 'National Capacity'],
    featuredInitiatives: [
      { code: '1', title: 'National Resilience Training Track', description: 'Structured professional pathways for flood resilience roles.' },
      { code: '2', title: 'Flood Science Fellowship Programme', description: 'Supporting emerging experts through applied research practice.' },
      { code: '3', title: 'Innovation & Knowledge Hub Network', description: 'Connecting institutions to scale practical resilience innovation.' },
    ],
    technologies: ['Learning Platforms', 'Simulation Tools', 'GIS Labs', 'Knowledge Portals', 'Training Dashboards'],
    expectedOutcomes: ['Stronger Technical Workforce', 'Improved Operational Skills', 'Faster Knowledge Transfer', 'Sustainable National Capacity'],
    relatedDocuments: [
      { title: 'Technical Blueprint', href: '/programme/blueprint' },
      { title: 'Guidelines', href: '/resources/training-materials' },
      { title: 'Research Reports', href: '/resources/reports' },
      { title: 'Datasets', href: '/research/open-data' },
      { title: 'Policy Briefs', href: '/resources/policy-briefs' },
    ],
    relatedNews: [
      { title: 'Capacity Building Cohort Graduates Across Regions', href: '/news/latest' },
      { title: 'University Network Expands Flood Science Collaboration', href: '/news/blog' },
      { title: 'Knowledge Exchange Series Launches New Training Modules', href: '/news/events' },
    ],
    relatedGallery: [
      { src: '/images/flood_gallery3.png', alt: 'Training and knowledge context', caption: 'Applied learning and collaborative resilience training.' },
      { src: '/images/flood_gallery4.png', alt: 'Response skills context', caption: 'Building practical skills for community and institutional teams.' },
      { src: '/images/flood_gallery2.png', alt: 'Knowledge transfer context', caption: 'Knowledge transfer supporting long-term resilience outcomes.' },
    ],
    cta: {
      title: 'Build National Capacity for Flood Resilience',
      description: 'Explore training pathways, knowledge resources, and partnerships that strengthen long-term resilience capability.',
      primary: { title: 'Explore Training Materials', href: '/resources/training-materials' },
      secondary: { title: 'Get Involved', href: '/get-involved' },
    },
  },
}
